### ISSUE TITLE
VK обновил интерфейс... не могу получить Токен

### ISSUE THREAD

**Issue by jorjik** [CrazyFreeMan/vkpost#6]
нужен совет; сейчас есть набор ID+Key http://take.ms/4Ho3a

при генерации токена получаю:

`{"error":"invalid_grant","error_description":"Code is invalid or expired."}`

**Comment by CrazyFreeMan** [comment]
Яке відношення має інтерфейс ВК до розширення? Навіщо створювати задачу з цього приводу?
Все описано у відповіді сервера вк. 
invalid_grant
Code is invalid or expired.
Увімкніть доступ, перевірте чи не пропустили єтап отримання ключа.
