### ISSUE TITLE
Настроил/запостил - ошибок нет, результата нет...

### ISSUE THREAD

**Issue by jorjik** [CrazyFreeMan/vkpost#7]
Сайт, проект http://freeweblance.ru/projects/web-dev/novyj-lending
Группа https://vk.com/club132614132
?!
вопрос в заголовке...

**Comment by CrazyFreeMan** [comment]
Логи смотреть. Это не Задача а индивидуальная проблема . Плуг устаревший

**Comment by jorjik** [comment]
Что значит устарел? - если у меня версия 0,2

В логах чисто

**Comment by jorjik** [comment]
Ага, нашёл - Error (User authorization failed: access_token was given to another ip address.)
** но тут похоже не легче

**Comment by CrazyFreeMan** [comment]
старел значит что не рекомендуется использовать. А ошибка написана довольно ясно "access_token was given to another ip address"   токен выдан для другого ИП, или отключить проверку или додавить исключение в настройках приложения ВК

**Comment by jorjik** [comment]
в настройках только OpenAPI - вкл/выкл

тут вроде есть ответ https://vk.com/topic-15957347_25001738

* В общем помучался пару часов и удалось решить путем добавления
"offline" в scope.



09.03.2017, Yaroslav<notifications@github.com> написал(а):

**Comment by jorjik** [comment]
вы напрасно закрыли - я этот вопрос не решил;

суппорт направляет к разработчику http://take.ms/l9h7E

**Comment by CrazyFreeMan** [comment]
Разработка и поддержка данного плагина не ведется.
